version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: cloudgo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudgo
    ports:
        - "5432:5432"
    restart: always