version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/cloudgo/bin/migrate up && /cloudgo/bin/api" ]

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: cloudgo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudgo
    ports:
        - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudgo -d cloudgo" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always